# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cosmos.streaming.v1 import grpc_pb2 as cosmos_dot_streaming_dot_v1_dot_grpc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cosmos/streaming/v1/grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListenerServiceStub(object):
    """ListenerService is the service for the Listener interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenDeliverBlock = channel.unary_unary(
                '/cosmos.streaming.v1.ListenerService/ListenDeliverBlock',
                request_serializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockRequest.SerializeToString,
                response_deserializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockResponse.FromString,
                _registered_method=True)
        self.ListenStateChanges = channel.unary_unary(
                '/cosmos.streaming.v1.ListenerService/ListenStateChanges',
                request_serializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesRequest.SerializeToString,
                response_deserializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesResponse.FromString,
                _registered_method=True)


class ListenerServiceServicer(object):
    """ListenerService is the service for the Listener interface
    """

    def ListenDeliverBlock(self, request, context):
        """ListenDeliverBlock is the corresponding endpoint for Listener.ListenDeliverBlock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenStateChanges(self, request, context):
        """ListenStateChanges is the corresponding endpoint for Listener.ListenStateChanges
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenDeliverBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ListenDeliverBlock,
                    request_deserializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockRequest.FromString,
                    response_serializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockResponse.SerializeToString,
            ),
            'ListenStateChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListenStateChanges,
                    request_deserializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesRequest.FromString,
                    response_serializer=cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.streaming.v1.ListenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.streaming.v1.ListenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListenerService(object):
    """ListenerService is the service for the Listener interface
    """

    @staticmethod
    def ListenDeliverBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.streaming.v1.ListenerService/ListenDeliverBlock',
            cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockRequest.SerializeToString,
            cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenDeliverBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenStateChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.streaming.v1.ListenerService/ListenStateChanges',
            cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesRequest.SerializeToString,
            cosmos_dot_streaming_dot_v1_dot_grpc__pb2.ListenStateChangesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
