# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: celestia_proto/cosmos/params/v1beta1/params.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'celestia_proto/cosmos/params/v1beta1/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1celestia_proto/cosmos/params/v1beta1/params.proto\x12$celestia_proto.cosmos.params.v1beta1\"3\n\x12QueryParamsRequest\x12\x10\n\x08subspace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"W\n\x13QueryParamsResponse\x12@\n\x05param\x18\x01 \x01(\x0b\x32\x31.celestia_proto.cosmos.params.v1beta1.ParamChange\";\n\x0bParamChange\x12\x10\n\x08subspace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t2\x88\x01\n\x05Query\x12\x7f\n\x06Params\x12\x38.celestia_proto.cosmos.params.v1beta1.QueryParamsRequest\x1a\x39.celestia_proto.cosmos.params.v1beta1.QueryParamsResponse\"\x00\x42-Z+github.com/cosmos/cosmos-sdk/x/params/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'celestia_proto.cosmos.params.v1beta1.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/cosmos/cosmos-sdk/x/params/types'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=91
  _globals['_QUERYPARAMSREQUEST']._serialized_end=142
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=144
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=231
  _globals['_PARAMCHANGE']._serialized_start=233
  _globals['_PARAMCHANGE']._serialized_end=292
  _globals['_QUERY']._serialized_start=295
  _globals['_QUERY']._serialized_end=431
# @@protoc_insertion_point(module_scope)
