# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/base/grpc/v2/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cosmos/base/grpc/v2/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!cosmos/base/grpc/v2/service.proto\x12\x13\x63osmos.base.grpc.v2\x1a\x19google/protobuf/any.proto\"5\n\x0cQueryRequest\x12%\n\x07request\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"7\n\rQueryResponse\x12&\n\x08response\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x1a\n\x18ListQueryHandlersRequest\"K\n\x19ListQueryHandlersResponse\x12.\n\x08handlers\x18\x01 \x03(\x0b\x32\x1c.cosmos.base.grpc.v2.Handler\"6\n\x07Handler\x12\x14\n\x0crequest_name\x18\x01 \x01(\t\x12\x15\n\rresponse_name\x18\x02 \x01(\t2\xd1\x01\n\x07Service\x12P\n\x05Query\x12!.cosmos.base.grpc.v2.QueryRequest\x1a\".cosmos.base.grpc.v2.QueryResponse\"\x00\x12t\n\x11ListQueryHandlers\x12-.cosmos.base.grpc.v2.ListQueryHandlersRequest\x1a..cosmos.base.grpc.v2.ListQueryHandlersResponse\"\x00\x42!Z\x1f\x63osmossdk.io/server/v2/api/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.base.grpc.v2.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037cosmossdk.io/server/v2/api/grpc'
  _globals['_QUERYREQUEST']._serialized_start=85
  _globals['_QUERYREQUEST']._serialized_end=138
  _globals['_QUERYRESPONSE']._serialized_start=140
  _globals['_QUERYRESPONSE']._serialized_end=195
  _globals['_LISTQUERYHANDLERSREQUEST']._serialized_start=197
  _globals['_LISTQUERYHANDLERSREQUEST']._serialized_end=223
  _globals['_LISTQUERYHANDLERSRESPONSE']._serialized_start=225
  _globals['_LISTQUERYHANDLERSRESPONSE']._serialized_end=300
  _globals['_HANDLER']._serialized_start=302
  _globals['_HANDLER']._serialized_end=356
  _globals['_SERVICE']._serialized_start=359
  _globals['_SERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
